---
listen:
  host: localhost
  port: 55756
mysql:
  db: stock
  host: localhost
  port: 3306
  user: stock
  pass: zTwa2mhCZCfQMqX7eQix
redis:
  host: localhost
  port: 6379
  db: 6
  pass: 3D6kiP36dYTK9X2a
logfile: stock.log