---
listen:
  port: 55756
mysql:
  db: stock
  host: mysql
  port: 3306
  user: stock
  pass: zTwa2mhCZCfQMqX7eQix
redis:
  host: redis
  port: 6379
  db: 6
  pass: pFG64SBbhGB56K8Cv5eZbrdQ
logfile: logs/stock.log
